[tool.black]
line-length = 119
skip-string-normalization = true

[tool.isort]
profile = "black"
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
line_length = 79
combine_as_imports = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = "test_*.py *_tests.py"
